spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:blog-test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080